name: local-build

on:
  workflow_dispatch:
    inputs:
      NAME:
        description: 'A random input name for the workflow'
        type: string

permissions:
  contents: write

jobs:
  local-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }'| sed 's/[",]//g' | sed 's/ //g')
          echo ::set-output name=VERSION::${PACKAGE_VERSION}

      - name: 展示版本
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            qinxiandiqi/van-blog:latest
            qinxiandiqi/van-blog:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            VAN_BLOG_VERSIONS=${{ steps.get_version.outputs.VERSION }}

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: generateReleaseNote
        run: node scripts/releaseNote.js
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGE.md
