name: arm

on:
  push:
    tags:
      - 'arm*'
permissions:
  contents: write
  packages: write

jobs:
  arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          TIMEVERSION=$(date "+%Y%m%d-%H%M%S")
          echo ::set-output name=VERSION::${TIMEVERSION}

      - name: 展示版本
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            qinxiandiqi/van-blog:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            VAN_BLOG_VERSIONS=${{ steps.get_version.outputs.VERSION }}
