name: test

on:
  push:
    tags:
      - 'test*'
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          TIMEVERSION=$(date "+%Y%m%d-%H%M%S")
          echo ::set-output name=VERSION::${TIMEVERSION}

      - name: 展示版本
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 打包镜像并推送
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VAN_BLOG_BUILD_SERVER=http://localhost:3000
            VAN_BLOG_VERSIONS=test-${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64
          push: true
          tags: |
            "docker.io/qinxiandiqi/van-blog:test-${{ steps.get_version.outputs.VERSION }}"

      # - name: 部署到测试环境
      #   uses: steebchen/kubectl@v2.0.0
      #   with:
      #     config: ${{ secrets.K8S_CONFIG_DATA }}
      #     command: set image  deployment/blog-test van-blog=mereith/van-blog:${{ steps.get_version.outputs.VERSION }}
